# Generated by Django 5.1.3 on 2024-11-19 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadOficial',
            fields=[
                ('entidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50, null=True)),
                ('url_oficial', models.URLField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('foto_id', models.BinaryField(null=True)),
                ('foto_perfil', models.BinaryField(null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido')], default='activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('reporte_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('ubicacion_latitud', models.FloatField(null=True)),
                ('ubicacion_longitud', models.FloatField(null=True)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(null=True)),
                ('foto_reporte', models.BinaryField(null=True)),
                ('foto_referencia', models.BinaryField(null=True)),
                ('estado_reporte', models.CharField(choices=[('abierto', 'Abierto'), ('en progreso', 'En Progreso'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('entidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.entidadoficial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilDeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reportes', models.IntegerField(default=0)),
                ('total_apoyos', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioEnReporte',
            fields=[
                ('comentario_id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reporte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ApoyoEnReporte',
            fields=[
                ('apoyo_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_apoyo', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reporte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]
